export const assets = [
  {
    symbol: "XAU/USD",
    name: "Gold",
    price: "2,365.40",
    change: "-0.42%",
    sentiment: "Bearish",
    risk: "High",
    accent: "bg-amber-500",
  },
  {
    symbol: "XAG/USD",
    name: "Silver",
    price: "30.84",
    change: "+0.18%",
    sentiment: "Neutral",
    risk: "Medium",
    accent: "bg-slate-400",
  },
  {
    symbol: "EUR/USD",
    name: "Euro / Dollar",
    price: "1.0824",
    change: "-0.21%",
    sentiment: "Bearish",
    risk: "Medium",
    accent: "bg-blue-500",
  },
  {
    symbol: "GBP/USD",
    name: "Pound / Dollar",
    price: "1.2738",
    change: "+0.09%",
    sentiment: "Bullish",
    risk: "Low",
    accent: "bg-emerald-500",
  },
  {
    symbol: "USD/JPY",
    name: "Dollar / Yen",
    price: "149.85",
    change: "+0.32%",
    sentiment: "Bullish",
    risk: "Medium",
    accent: "bg-rose-500",
  },
  {
    symbol: "USD/CHF",
    name: "Dollar / Franc",
    price: "0.9012",
    change: "-0.15%",
    sentiment: "Bearish",
    risk: "Medium",
    accent: "bg-red-500",
  },
  {
    symbol: "AUD/USD",
    name: "Aussie / Dollar",
    price: "0.6584",
    change: "+0.22%",
    sentiment: "Bullish",
    risk: "Medium",
    accent: "bg-purple-500",
  },
  {
    symbol: "USD/CAD",
    name: "Dollar / Loonie",
    price: "1.3720",
    change: "-0.08%",
    sentiment: "Bearish",
    risk: "Low",
    accent: "bg-cyan-500",
  },
  {
    symbol: "BTC/USD",
    name: "Bitcoin",
    price: "62,648.63",
    change: "+0.62%",
    sentiment: "Bullish",
    risk: "High",
    accent: "bg-orange-500",
  },
  {
    symbol: "ETH/USD",
    name: "Ethereum",
    price: "1,788.79",
    change: "+0.83%",
    sentiment: "Bullish",
    risk: "High",
    accent: "bg-indigo-500",
  },
];

export const newsItems = [
  {
    title: "Fed signals rates may stay higher for longer",
    source: "Macro desk",
    impact: "USD bullish, gold bearish",
    confidence: "82%",
    risk: "High",
    summary: "Higher-for-longer rate expectations can support USD strength and reduce short-term gold demand.",
  },
  {
    title: "US inflation data beats market forecast",
    source: "Economic release",
    impact: "High volatility expected",
    confidence: "76%",
    risk: "High",
    summary: "Hot inflation increases uncertainty around rate cuts and can create fast moves across USD pairs.",
  },
  {
    title: "Risk sentiment improves before New York open",
    source: "Market flow",
    impact: "Safe-haven pressure possible",
    confidence: "68%",
    risk: "Medium",
    summary: "When risk appetite improves, gold can face pressure as traders rotate into higher-risk assets.",
  },
];

export const trades = [
  {
    pair: "XAU/USD",
    setup: "Rejected resistance after USD bullish headline",
    entry: "2368.20",
    stop: "2376.00",
    target: "2352.00",
    grade: "B+",
  },
  {
    pair: "EUR/USD",
    setup: "Bearish continuation after CPI surprise",
    entry: "1.0830",
    stop: "1.0872",
    target: "1.0750",
    grade: "A-",
  },
];
